(function(g){
"use strict";
if(g.__CM90_PLUS__)return;g.__CM90_PLUS__=true;
var ST={eventCounter:0,previousHash:"GENESIS",quarantined:[],decoys:[],canaries:[],blocked:0,replayAttempts:0,seenEvents:new Set(),lastRequests:[],rateWindow:4000,maxRequests:12,integrity:"VALID",incidentState:"NORMAL",networkMode:"OFFLINE"};
function escapeHTML(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
async function digest(text){if(g.crypto&&crypto.subtle){var buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(buf)).map(function(x){return x.toString(16).padStart(2,"0");}).join("");}var h=2166136261;for(var i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
function validateInput(input){if(!input||typeof input!=="object"||Array.isArray(input))return false;var keys=Object.keys(input);if(keys.length>50)return false;for(var i=0;i<keys.length;i++){if(keys[i].length>100)return false;if(/__proto__|constructor|prototype/i.test(keys[i]))return false;}try{if(JSON.stringify(input).length>20000)return false;}catch(e){return false;}return true;}
function rateAllowed(){var now=Date.now();ST.lastRequests=ST.lastRequests.filter(function(t){return now-t<ST.rateWindow;});if(ST.lastRequests.length>=ST.maxRequests){ST.blocked++;log("ALERT","Rate limit exceeded · input blocked");return false;}ST.lastRequests.push(now);return true;}
function replayCheck(id){if(!id)return true;if(ST.seenEvents.has(id)){ST.replayAttempts++;ST.blocked++;log("ALERT","Replay blocked · "+id);return false;}ST.seenEvents.add(id);return true;}
function log(type,msg){ST.eventCounter++;var feed=document.getElementById("cmpFeed");if(!feed)return;var div=document.createElement("div");div.textContent="["+new Date().toLocaleTimeString()+"] "+type+" · "+msg;feed.insertBefore(div,feed.firstChild);while(feed.children.length>80)feed.removeChild(feed.lastChild);}
function paint(){function set(id,v){var el=document.getElementById(id);if(el)el.textContent=v;}set("cmpState",ST.incidentState);set("cmpQuarantine",String(ST.quarantined.length));set("cmpBlocked",String(ST.blocked));set("cmpReplay",String(ST.replayAttempts));set("cmpDecoys",String(ST.decoys.length));set("cmpCanary",String(ST.canaries.length));set("cmpIntegrity",ST.integrity);set("cmpNetwork",ST.networkMode);}
async function zeroTrustGate(input){if(!rateAllowed())return{accepted:false,reason:"RATE_LIMIT"};if(!validateInput(input)){ST.blocked++;ST.quarantined.push({t:Date.now(),reason:"SCHEMA"});ST.incidentState="QUARANTINE";log("ALERT","Schema firewall rejected input");paint();return{accepted:false,reason:"SCHEMA_FAILURE"};}if(!replayCheck(input.eventId))return{accepted:false,reason:"REPLAY"};var hash=await digest(ST.previousHash+JSON.stringify(input));ST.previousHash=hash;log("OK","Input passed structural boundary · hash "+hash.slice(0,10));ST.incidentState="NORMAL";paint();return{accepted:true,reason:"VALIDATED",hash:hash};}
function createDecoy(){var d={id:"DECOY-"+Date.now().toString(36),classification:"SYNTHETIC_HUMAN_LIKE_DECOY",realPerson:false,realAccount:false,locationModel:["Zimbabwe","South Africa","United Kingdom","Southern Africa","Diaspora — unspecified"][ST.decoys.length%5],lifecycle:"EPHEMERAL"};ST.decoys.push(d);ST.lastDecoy=d;var out=document.getElementById("cmpDecoy");if(out)out.textContent="SYNTHETIC DECOY\nID "+d.id+"\nREAL HUMAN: NO\nREGION MODEL: "+d.locationModel+"\nThis is not a family member and holds no credentials.";log("OK","Synthetic human-like decoy generated");paint();return d;}
function createCanary(){var d=ST.lastDecoy||createDecoy();d.canary=true;d.canaryId="CANARY-"+Date.now().toString(36);ST.canaries.push(d);log("WARNING","Canary node armed · synthetic monitoring object");paint();return d;}
function mount(){if(document.getElementById("cm90-plus"))return;var s=document.createElement("section");s.id="cm90-plus";s.style.cssText="margin:12px;padding:14px;border:1px solid #294256;border-radius:16px;background:#08121b;color:#cfe8ff;font:13px/1.45 system-ui";s.innerHTML="<div style='letter-spacing:.14em;color:#4de7ff'>CM90+ ZERO-TRUST GATE</div><p style='opacity:.75'>Outside → validate → quarantine → family simulation. No outbound attack. No curse return to people. Offline by design.</p><div>STATE <b id='cmpState'>NORMAL</b> · NET <b id='cmpNetwork'>OFFLINE</b> · INTEGRITY <b id='cmpIntegrity'>VALID</b></div><div>QUARANTINE <b id='cmpQuarantine'>0</b> · BLOCKED <b id='cmpBlocked'>0</b> · REPLAY <b id='cmpReplay'>0</b> · DECOYS <b id='cmpDecoys'>0</b> · CANARY <b id='cmpCanary'>0</b></div><div style='margin:8px 0;display:flex;flex-wrap:wrap;gap:8px'><button type='button' id='cmpTestBoundary'>Test boundary</button><button type='button' id='cmpGenerateDecoy'>Generate decoy</button><button type='button' id='cmpCanaryTest'>Canary test</button><button type='button' id='cmpQuarantineBtn'>Quarantine test</button><button type='button' id='cmpReplayBtn'>Replay test</button></div><pre id='cmpDecoy' style='background:#05080e;padding:8px;white-space:pre-wrap'>NO SYNTHETIC DECOY CURRENTLY DISPLAYED.</pre><div id='cmpFeed' style='max-height:160px;overflow:auto;background:#05080e;padding:8px'></div>";(document.querySelector("main")||document.body).appendChild(s);s.querySelectorAll("button").forEach(function(b){b.style.cssText="background:#0c141e;color:#eaf3ff;border:1px solid #1d2c3d;border-radius:8px;padding:8px 10px";});document.getElementById("cmpTestBoundary").onclick=function(){zeroTrustGate({eventId:"TEST-"+Date.now(),source:"LOCAL_TEST",type:"synthetic-pattern"});};document.getElementById("cmpGenerateDecoy").onclick=createDecoy;document.getElementById("cmpCanaryTest").onclick=function(){var c=createCanary();ST.incidentState="SUSPICIOUS";ST.quarantined.push({type:"CANARY_ACCESS"});log("ALERT","Synthetic canary accessed · quarantined locally");paint();};document.getElementById("cmpQuarantineBtn").onclick=function(){zeroTrustGate({eventId:"BAD",__proto__:"x"});};document.getElementById("cmpReplayBtn").onclick=function(){var id="REPLAY-"+Date.now();zeroTrustGate({eventId:id,type:"synthetic"}).then(function(){return zeroTrustGate({eventId:id,type:"synthetic"});});};}
g.CM90PLUS={receive:zeroTrustGate,createDecoy:createDecoy,createCanary:createCanary,state:ST};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){mount();paint();log("OK","CM90+ zero-trust boundary initialised");});else{mount();paint();log("OK","CM90+ zero-trust boundary initialised");}
})(typeof window!=="undefined"?window:globalThis);
